spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/invoiceflow_db
spring.datasource.username=invoiceflow_user
spring.datasource.password=invoiceflow_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080

# JWT Settings
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# 24 hours
application.security.jwt.expiration=86400000
